config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'time_entries#index'

  resources :time_entries, only: %i[index edit update] do
    collection do
      post :start_timer 
      put :stop_timer
    end  
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :user

  validates :starts_at, presence: true
  validates :finishes_at, presence: true, if: -> { self.persisted? }
  validate :only_one_running, if: -> { self.new_record? } 
  validate :start_at_less_than_finish_at

  private

  def only_one_running
    errors.add(:running, 'already running') if user&.timer_running?
  end

  def start_at_less_than_finish_at
    return unless finishes_at.present?
    errors.add(:finishes_at, 'cannot be earlier than starts at') if finishes_at < starts_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :time_entries, dependent: :destroy

  def current_timer
    time_entries.find_by(finishes_at: nil)
  end  

  def timer_running?
    current_timer.present?
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_entry, only: %i[edit update]

  def index
    @time_entries = current_user.time_entries.order(id: :desc)
  end

  def edit
  end

  def update
    @time_entry.edited = true
    if @time_entry.update(time_entry_params)
      redirect_to time_entries_path, notice: "Time entry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def start_timer
    @time_entry = current_user.time_entries.new(starts_at: Time.now)
    if @time_entry.save
      flash[:notice] = "Timer was successfully started"
    else
      flash[:notice] = "Timer can't be started"
    end
    redirect_to time_entries_path
  end

  def stop_timer
    @time_entry = current_user.current_timer
    if @time_entry && @time_entry.update(finishes_at: Time.now)
      flash[:notice] = "Timer was successfully stopped"
    else
      flash[:notice] = "Timer can't be stopped"
    end  
    redirect_to time_entries_path
  end

  private
    def set_time_entry
      @time_entry = current_user.time_entries.find(params[:id])
    end

    def time_entry_params
      params.require(:time_entry).permit(:starts_at, :finishes_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formated_time(time, filling = 'None')
    return filling unless time
    time.strftime('%Y-%m-%d %I:%M %p')
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Himama Timer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container" style="padding-top: 2rem;">
      <% if current_user.present?%>
       Welcome, <%=current_user.email %>
      <% end %>
      <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-danger mb-4" ) if current_user.present? %>
      <br/><br/>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/time_entries/_clock_in_button.erb
<%= link_to 'Clock In', start_timer_time_entries_path, method: :post, class: "btn btn-success" %>

app/views/time_entries/_clock_out_button.erb
<%= link_to 'Clock Out', stop_timer_time_entries_path, method: :put, class: "btn btn-info" %>

app/views/time_entries/_form.html.erb
<div class="col-md-6">
<%= form_with(model: time_entry, local: true) do |form| %>
  <% if time_entry.errors.any? %>
    <div id="error_explanation" class="alert alert-danger m-3">
      <p><%= pluralize(time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</p>

      <ul>
        <% time_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

      
    </div>
  <% end %>
  <div class="form-group field">
  <%= form.label :starts_at, class: "h3" %><br>
  <%= form.datetime_field :starts_at,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
</div>

<div class="form-group field">
  <%= form.label :finishes_at, class: "h3" %><br>
  <%= form.datetime_field :finishes_at,  class: "form-control mb-2 mr-sm-2 mb-sm-0" %>
</div>
 

  <div class="actions">
    
    <%= form.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

</div>

app/views/time_entries/edit.html.erb
<h1>Editing Time Entry</h1>

<%= render 'form', time_entry: @time_entry %>

<%= link_to 'Back', time_entries_path, class: "btn btn-info" %>

app/views/time_entries/index.html.erb
<% unless notice.nil?%>
<div class="alert alert-success m-3" role="alert" id="notice">
  <%= notice %>
</div>
<% end %>

<div id="timer-button">
  <% if current_user.timer_running? %>
    <%= render 'clock_out_button.erb' %>
  <% else %>
    <%= render 'clock_in_button.erb' %>
  <% end %>
</div>


<h1>Himama Timesheet</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr >
      <th>Starts At</th>
      <th>Finishes At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |time_entry| %>
      <tr>
        <td><%= time_entry.starts_at.to_formatted_s(:long) %></td>
        <td> 
        <% if time_entry.finishes_at %>
        <%= time_entry.finishes_at.to_formatted_s(:long)%>
        <% else %>
        Running ...
        <% end %>
        </td>
        <td>
          <% if time_entry.finishes_at %>
            <%= link_to 'Edit', edit_time_entry_path(time_entry), class: "btn btn-warning" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>